version: '3'

services:
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    image: postgres:14.3-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat